
Instance: 5770866
InstanceOf: QuestionnaireResponse
Usage: #example
* meta.versionId = "1"
* meta.lastUpdated = "2024-05-29T11:33:28.000-04:00"
* meta.source = "#0lIZjVUX1cOEzu37"
* meta.profile = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaireresponse|3.0"
* meta.tag.code = #"lformsVersion: 36.0.5"
* questionnaire = "Questionnaire/PHQ-15-Questionnaire"
* status = #completed
* subject = Reference(Patient/5770846) "Abbey, Robyn"
* authored = "2024-05-29T15:33:27.378Z"
* author = Reference(Practitioner/smart-Practitioner-71482713) "Susan Clark"
* author.type = "Practitioner"
* item[0].linkId = "/69671-6"
* item[=].text = "Stomach pain"
* item[=].answer.valueCoding = $loinc#LA18334-5 "Not bothered"
* item[+].linkId = "/69672-4"
* item[=].text = "Back pain"
* item[=].answer.valueCoding = $loinc#LA18336-0 "Bothered a lot"
* item[+].linkId = "/69673-2"
* item[=].text = "Pain in your arms, legs, or joints (knees, hips, etc.)"
* item[=].answer.valueCoding = $loinc#LA18335-2 "Bothered a little"
* item[+].linkId = "/69674-0"
* item[=].text = "Menstrual cramps or other problems with your periods"
* item[=].answer.valueCoding = $loinc#LA18335-2 "Bothered a little"
* item[+].linkId = "/69717-7"
* item[=].text = "Pain or problems during sexual intercourse"
* item[=].answer.valueCoding = $loinc#LA18335-2 "Bothered a little"
* item[+].linkId = "/69675-7"
* item[=].text = "Headaches"
* item[=].answer.valueCoding = $loinc#LA18334-5 "Not bothered"
* item[+].linkId = "/69676-5"
* item[=].text = "Chest pain"
* item[=].answer.valueCoding = $loinc#LA18334-5 "Not bothered"
* item[+].linkId = "/69677-3"
* item[=].text = "Dizziness"
* item[=].answer.valueCoding = $loinc#LA18336-0 "Bothered a lot"
* item[+].linkId = "/69678-1"
* item[=].text = "Fainting spells"
* item[=].answer.valueCoding = $loinc#LA18335-2 "Bothered a little"
* item[+].linkId = "/69679-9"
* item[=].text = "Feeling your heart pound or race"
* item[=].answer.valueCoding = $loinc#LA18336-0 "Bothered a lot"
* item[+].linkId = "/69680-7"
* item[=].text = "Shortness of breath"
* item[=].answer.valueCoding = $loinc#LA18335-2 "Bothered a little"
* item[+].linkId = "/69681-5"
* item[=].text = "Constipation, loose bowels, or diarrhea"
* item[=].answer.valueCoding = $loinc#LA18335-2 "Bothered a little"
* item[+].linkId = "/69682-3"
* item[=].text = "Nausea, gas, or indigestion"
* item[=].answer.valueCoding = $loinc#LA18335-2 "Bothered a little"
* item[+].linkId = "/69731-8"
* item[=].text = "Feeling tired or having low energy"
* item[=].answer.valueCoding = $loinc#LA18335-2 "Bothered a little"
* item[+].linkId = "/69732-6"
* item[=].text = "Trouble sleeping"
* item[=].answer.valueCoding = $loinc#LA18335-2 "Bothered a little"
* item[+].linkId = "/70273-8"
* item[=].text = "Patient health questionnaire 15 item total score"
* item[=].answer.valueDecimal = 15